### PR TITLE
Postponing doctrine flush during product save

### PR DESCRIPTION
**Pull request by Mesuva**
Potential fix for #252

### CODE REVIEW

**Comment by barkingtuna** [comment]
I swapped out all the code and now get:
An unexpected error occurred.
Unrecognized field: pvSort

**Comment by Mesuva** [comment]
You'll need to trigger an upgrade of the package - pvSort is a newly added field

**Comment by barkingtuna** [comment]
Thanks... I did that and now the Description and Short Description text area fields don't populate/appear so I can in put date. The Title show up, but there's no way to enter the data. I installed a fresh V1.2 and 
v1 2_description

**Comment by Mesuva** [comment]
I'm not seeing that - javascript errors?

**Comment by barkingtuna** [comment]
It's all good... I scrapped everything and started over. No issues. Sorry to waste your time.

**Comment by Mesuva** [comment]
Not wasting anyone time, I appreciate the testing!

Any idea what caused it though?

**Comment by barkingtuna** [comment]
I installed a different theme on top of what I'd built it in initially and as you assumed, there were theme based Javascript errors that compounded across the entire site. It affected all content areas, not just the product. Clean install fixed it.

**Comment by barkingtuna** [comment]
UPDATE... I just enabled https://www.concrete5.org/marketplace/addons/icons-for-redactor in the Rich Text Editor and the error is back. That particular addon is the culprit.

**Pull request merged**
