### PR TITLE
For select the current status

### PR DESCRIPTION
**Pull request by midhun1993**

### CODE REVIEW

**Comment by Mesuva** [comment]
Make sense to me!

**Comment by smansfield** [comment]
He didn't explain it, but this is a fix.
The order status select field was passing the status value as the currently selected option. When using the $form->select() helper, you have to pass the key of the item you want selected instead. In this context, that equates to the handle instead of the display value. With the array 
`array('incomplete' => 'Will not deliver', 'proccessing' => 'Processing')` you have to pass the value 'incomplete' as the third argument instead of 'Will not deliver'.
See this portion of the body of select() in _concrete/src/Form/Service/Form.php_:
```
foreach ($optionValues as $k => $text) {
    $str .= '<option value="' . $k . '"';
    if ((string) $k === (string) $selectedValue) {
        $str .= ' selected="selected"';
    }
    $str .= '>' . $text . '</option>';
}
```
$selectedValue, the third argument, is compared against $k, the key in the options array.
Try editing an order status without his fix, when you hit submit it won't save. If you apply his fix it will.
Hope this helps!

**Comment by Mesuva** [comment]
Thanks @smansfield 

The thing to note with this drop down is that it really was just to allow you to pick a status to change the order to, not necessarily reflect the current status. When you hit update the picked order status adds to the list above it, so the last active fulfilment status is the one at the top of the list.

But I agree that it makes sense to have the dropdown also reflect this.

**Comment by mkly** [comment]
Hi @Mesuva just clear things up a bit. Passing the name of the status as the default value parameter doesn't do anything because it can never resolve to `true`. It would have exactly the same effect to simply leave it off. So in this case the fix is either to apply this pull request or remove the call the `$order->getStatusName()` as it can never resolve to `true` If you prefer that, let me know and I'll send in a PR.

Happy Friday. :beers:

**Comment by Mesuva** [comment]
Happy to accept any PR to tidy this up. Being honest I'm a bit confused whether this is suggesting it needs more work or there's nothing more to do here!

**Comment by mkly** [comment]
This PR looks good. That parameter is the one that sets what the selected value is. Which lines up with the HTML `value` attribute. The `$orderStatuses` array has keys(which is what sets the `value` attribute) that are handles as opposed to names. So `getStatus()` can never match a handle and essentially is the same as leaving it out.  Hope that makes sense. Personally, I would merge this as is. Thanks for taking the time for a second look.

**Pull request closed without merging**
