### PR TITLE
Related product, plus sorting by price

### PR DESCRIPTION
**Pull request by Mesuva**
Allows products to have a listed of related products, with drag and drop sorting.
The Product List block has the ability to filter to show these related products for a product, either on the current page or a specified product. 
Also added in sorting by price, might be handy

### CODE REVIEW

**Comment by Mesuva** [comment]
Would love someone to give this a test!

**Comment by typoman76** [comment]
Uhh. Cool! Hope I find some time :-)

**Comment by krebbi** [comment]
I get 

An exception occurred while executing 'INSERT INTO AttributeSets (asHandle, asName, akCategoryID, asIsLocked, asDisplayOrder, pkgID) VALUES (?, ?, ?, ?, ?,?)' with params ["order_choices", "Other Customer Choices", "34", 1, 2, "24"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'order_choices' for key 'asHandle'

when updating this branch.

**Comment by krebbi** [comment]
when trying to add a related product i get:

An exception occurred while executing 'SELECT t0.id AS id1, t0.pID AS pID2, t0.relatedPID AS relatedPID3, t0.relatedSort AS relatedSort4, t0.pID AS pID5, t0.relatedPID AS relatedPID6 FROM CommunityStoreProductRelated t0 WHERE t0.pID = ?' with params [3]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c5dev.CommunityStoreProductRelated' doesn't exist

**Comment by Mesuva** [comment]
@krebbi - so you weren't able to upgrade the package? That would explain your  'c5dev.CommunityStoreProductRelated' doesn't exist error message.

The Duplicate entry 'order_choices' for key 'asHandle' isn't something I've seen myself, I'll take a look at that

**Pull request merged**
