### PR TITLE
Shipping instructions

### PR DESCRIPTION
**Pull request by Mesuva**
This adds in an optional 'delivery instructions' field within the shipping selection in the checkout.
Although this could potentially be handled by an order attribute, I think this field is so commonly used/expected, and specific in purpose that it makes sense to include it as a core field - it then shows on order emails and screens next to the shipping method.

(fix other fixes as well)

### CODE REVIEW

**Comment by MichaelMaar** [comment]
Ronny and I had a long discussion last night about exactly this. And I am a little split in my mind here. I just added something similar, but called it (Additional information to "shop company name"). This can't be done hard-coded because the nature of the label text. It has to be an order attribute. Here is an example.
screenshot_56

**Comment by Mesuva** [comment]
Your example is perfect for order attributes, and a great example of why they are needed.

My addition here is just a way for the field to be included 'natively'. It's off by default, and you can simply leave it off if you want to use attributes instead. 

My thinking with this is that this field is so commonly offered on checkout screens, I thought it would make more sense to have it a single checkbox enable, rather than having to create a new attribute. It's also closely related to shipping, so it will appear directly after the shipping method name, rather than in a list of attributes (which may or may not relate to shipping).

**Comment by MichaelMaar** [comment]
OK, I see. If it comes after Shipping I see the difference. We made a lot on the "Order Attributes2" branch last night. And it is now running on a live shop site!

**Comment by Mesuva** [comment]
screen shot 2016-05-27 at 3 23 01 pm

screen shot 2016-05-27 at 3 22 16 pm

**Pull request merged**
