### PR TITLE
Add "Electronic Delivery Fee" Surcharge (as Shipping Method)

### PR DESCRIPTION
**Pull request by macserv**
To facilitate sales via Square, and allow the processing fees to be accurately applied to an order, I've implemented the concept of an "Electronic Delivery Fee," implemented as a Shipping Method.  This approach applies the surcharge to the entire order, which is appropriate for assessing per-transaction payment processing fees.

An Electronic Delivery Fee can be configured to apply both a fixed rate and a percentage of the order total.  In the example below, Square's online transaction fee (30¢ + 2.9%) will be applied.

image

I'm sure that there are plenty of edge cases that I haven't considered and other areas for improvement (e.g., it's an odd user experience to have this show up as "Shipping"... could possibly implement this as a new "Processing" surcharge at the same level as Shipping and Tax), however, "the perfect is the enemy of the good."  I've already put this code into production for several sales scenarios, including event registrations and merchandise sales, and it definitely got the job done.

### CODE REVIEW

**Comment by Mesuva** [comment]
Thanks for this, I can see a few use-cases here. 

Interestingly, here in the UK my understanding is that adding this kind of additional charge for credit card processing has been banned, you can't charge more due to processing via card.

My gut feeling with this kind of functionality is that it should be provided as add-on, rather than being added to the core of Community Store.

I do agree it's a bit unusual to have this appear as a shipping option, but I totally see why you've done it this way as there's currently no other way to do it. I think Community Store may need the ability to have line items in an order that don't necessarily link to a product - then an add-on could use the cart events to add additional items such as surcharges, booking fees, free gifts, that kind of thing. I'll give this some thought when I do my next burst of work on the store, which hopefully should be soon.

**Comment by macserv** [comment]
Sure thing, happy to contribute.  Like I said, there are a lot of things to consider, but I felt it was good enough to land in the tree for the time being; without it, the store was, essentially, useless to me.  In the long term, I really like the idea of abstracting out surcharges

Side note: I find it really strange that it would be illegal to assess the processing fee directly and accurately.  In reality, no vendor is going to eat those fees, they would just try to pass it on it per-product.  I found that when I tried that approach— which seemed easier because it didn't involve any modifications— I ended up over-charging customers in the aggregate.  Seems like another well-intentioned law that ends up being harmful.

**Comment by Mesuva** [comment]
My impression of the law is that it's not so much an issue about charging to cover the fee, it's the concern over hiding it until the end of the transaction. Many have abused this historically and have added much higher transaction fees than justified.

It's perhaps a similar nature to how in Australia prices have to be advertised _including_ tax - the price you see is what you pay, as opposed to seeing a price and then paying a different price at the checkout. 

I personally detest it when ticketing companies will advertise a ticket as $50, for example, but you end up paying $60, because they tack on other fees and rubbish in the checkout. Advertising a ticket as $50 then is wrong, as you can't obtain it for that price.

**Comment by Mesuva** [comment]
I think I'll close this one for now, as I still think it's better handled as a stand-alone add-on.

**Comment by macserv** [comment]
Any pointers for how to implement this as an add-on?

**Comment by Mesuva** [comment]
I'd use this as a base for the add-on: https://github.com/concrete5-community-store/community_store_shipping_example

And the code you created in the PR should be able to be pretty much copied and pasted in, nearly all the code would be the same, you'd just need to change some of the namespaces. 

Keep in mind there are a few other shipping methods you can check out the pattern: https://github.com/concrete5-community-store

**Comment by macserv** [comment]
Awesome, thanks!

**Pull request closed without merging**
