### PR TITLE
Events: added cart events on add, update, remove and clear

### PR DESCRIPTION
**Pull request by agentsquidflaps**
Based on issue https://github.com/concrete5-community-store/community_store/issues/471

### CODE REVIEW

**Comment by agentsquidflaps** [comment]
Thanks for checking it out so quickly! 

You're right, I should change the terminology to match the rest of the store to 'cart' and I shall change the event names to more closely match 'on_community_store_noun_action'.

However, I'd argue that keeping them in constants would mean that, if in future, the event naming convention changes, then anyone doing an update to existing code won't have to change their event names, so it'd look something like...

`\Events::addListener(CommunityStoreCartEvent::CART_PRE_ADD, function ($event) {
    // do something here
});`

I'd also suggest that keeping the CART_ACTION would be beneficial for anyone needing to do something based on every cart action. Otherwise they'd need to add an event for add, update, remove, clear. But I have been wrong before 😂

**Comment by Mesuva** [comment]
I get your point with the constants, if we go down that line I'd say we should define all of them used in the store that way, and perhaps add a few comments in as well so they're all listed together in the one spot (which is handy)

Also understand what you mean about the cart actions, leave that in for now, I'm just struggling to come up with a scenario where you'd need to respond to a cart action, but not a specific action to do with the cart.

**Comment by agentsquidflaps** [comment]
I had a use case in that I needed to add an additional product and quantity depending on the product options that had been chosen. So, more specifically, if an order item had gift wrapping, then I needed to loop through all of the items in a cart, check if they had gift wrapping and add a product with x quantity depending on the result and remove if there were none

**Comment by Mesuva** [comment]
Ah yep, good example!

**Comment by agentsquidflaps** [comment]
Thank you again for your quick response and considerations @Mesuva

**Comment by Mesuva** [comment]
I've merged your code in, with a few adjustments here and there.
For testing, i've also updated the event example package, to include the new events:
https://github.com/concrete5-community-store/community_store_event_example

If you have a chance to test out and/or review the current master branch in terms of this new functionality that would be great

**Comment by agentsquidflaps** [comment]
Apologies for the delay, I've been very busy! But I can confirm that all the events seem to fire as expected!

**Pull request closed without merging**
