### PR TITLE
Apply discounts to subtotal as well as shipping

### PR DESCRIPTION
**Pull request by mkly**
* Apply discounts to subtotal as well as shipping

### CODE REVIEW

**Comment by mkly** [comment]
I feel like I might be missing something obvious here so definitely look this one over. From what I'm seeing these discounts are only applying in the cart to shipping without this change. Apologies if this is way off base.

**Comment by Mesuva** [comment]
I don't think this is quite right, but that's because it's pretty spread out logic.

When it's a discount that just takes off from the subtotal or the shipping (a type of 'value') that logic happens within the Calculator class. But any other kind of product discount needs to directly adjust the displayed product prices, so it gets applied within the Product objects themselves.  The applicable discounts (i.e. the ones that are valid, for the user and/or code supplied), are passed to the Product objects in the cart and then used as part of their price calculation. 

It's around this bit here:
https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Product/Product.php#L662
and then the actual maths is done here:
https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Discount/DiscountRule.php#L119

Note that 'percentage', 'value_all', and 'fixed' are handled in the DiscountRule, effectively the other three discount types.

Part of the confusion might come down to the wording:

**Percentage** - deducts from individual products that match
**Deduct value once** -  deducts from _subtotal_ if any product(s) in the cart match rules
**Deduct value from each matching item** - deducts from individual products that match
**Change to value** - changes price of individual products that match

Deduct value once ('value') is sort of the odd one out here, hence why it's in Calculator

**Comment by Mesuva** [comment]
I hate how these classes are all so tightly coupled to each other, but when all these items interplay it's pretty tricky.

**Comment by mkly** [comment]
Okay. That makes a lot more sense. I felt like it had to be something I was missing. I very much appreciate your taking the time to clear that up in such detail. Closing.

**Pull request closed without merging**
