### PR TITLE
Config is not exist

### PR DESCRIPTION
**Pull request by tao-s**
typo?

### CODE REVIEW

**Comment by Mesuva** [comment]
Going forward we're trying to avoid using the aliases of classes, instead, it's case of adding the full use statement for the class at the top of the file. I've done this instead, thanks for picking it up.

**Comment by tao-s** [comment]
@Mesuva Sorry, I'm little bit lazy. 
BTW, I'm translating this package to Japanese, so how do I send the language files to this repository? upload to transfix? send pull request to this repository?

**Comment by Mesuva** [comment]
No apology needed - it's only recently I've become aware of the recommendation to not use the aliases, and that we've cleaned it up in community store.

With the translations that's a really good question - there is a plan to make Community Store available on the official translation system for concrete5 (the one used to translate marketplace packages), but that hasn't happened yet.  

I'll put up an announcement somewhere when there's an update regarding this.

I don't think Transifex is part of the process anymore.

In the meantime you're welcome to do a pull request to include the language files, at least they are then stored here for reference.

**Comment by tao-s** [comment]
Ok, I'll send PR. Thank you.

**Pull request closed without merging**
