### PR TITLE
Filter out non-existent variations

### PR DESCRIPTION
**Pull request by evgk**

### CODE REVIEW

**Comment by evgk** [comment]
A note on implementation - with those lines:
           var tmp = variation.join('_');
           var tmp1 = variation.slice(0).reverse().join('_');

given a variation of "1,3", it'll only check for 1_3 and 3_1 in variation data array. Since there might be more then 2 options, a more generic approach is to check all permutations of a variation(so for "1,2,3", check 1_2_3, 1_3_2, 3_2_1, 2_3_1,etc..) to account for different ordering of keys, but not sure it's that useful, there are very few setups with more then 2 options and ordering in variationData is rarely inconsistent(although it can be).

**Comment by evgk** [comment]
> And I don't think we should hide options when they aren't available, because they still might need to be referenced.

Hmm... it's just seems weird to show the non-existing variations - suppose you have a product-type attribute and a bunch of sizes, so you have variations based on those. Showing all attributes instead of only the ones that exist means you can see those in frontend, which might be a totally nonsensical combination - certain sizes should only go to a certain product type... This is an example:

https://ariakaysboutique.com/products/baseball-babe-set

**Comment by evgk** [comment]
In the example above, showing all sizes would also mean a huge number of options in the  "Size" selector with only a handful of them selectable per each product type.

**Comment by evgk** [comment]
A more common example - suppose you have sizes: 1,2,3,4,5,6,7,8,9 for "red",  same sizes for "green", but for "blue" you only have 10 and 11 - so if the customer selects "blue", how does it make sense to have the customer click through 1 to 9 sizes to understand that they are out of stock? Wouldn't it make much more sense to just remove them from the selector?

**Comment by Mesuva** [comment]
I understand your example, but customers wouldn't click through each size - they would pick the size they are looking for and see it is out of stock. But in being able to pick it, they would be able to potentially see an image of that combination and a price, and effectively be shown that the product would normally be available. They then might enquire or come back later to order, whereas if you hide the option you give the impression that the combination never exists.

With your example and baseball babe set, personally I wouldn't be grouping products like that, the products seem to be different kinds of things, rather than minor variations - I'd create seperate products for them.

**Comment by evgk** [comment]
> With your example and baseball babe set, personally I wouldn't be grouping products like that, the products seem to be different kinds of things, rather than minor variations - I'd create seperate products for them.

It wasn't my choice, but the customers - and I think it's a legit use-case here, it would be weird to create 6 products out of what is essentially a single product.


> But in being able to pick it, they would be able to potentially see an image of that combination and a price, and effectively be shown that the product would normally be available

But that's a VERY wrong consideration in the above! What kind of "image" and "price" would they see on NONEXISTENT variation? Note I am not talking about the out of stock ones - those should be displayed.

**Comment by evgk** [comment]
The point is that it should be possible to distinguish cases when the variation is out of stock and when it doesn't exist -> it's an invalid combination of options, in which case it's better to not show it at all.

**Comment by Mesuva** [comment]
That I agree with, I can see cases where you really wouldn't want a particular combination offered. 

But I'd say that that's more of an exception to the rule, and it's more likely that you would want to show that combo.  
In the example your client has configured, I'd say that's actually just setting up a product wrong. 
A bow is not a variation on a shirt, for example. A variation is taking the base product and changing it slightly, either something like a colour/size combo or changing some inclusion, not changing it completely to a different product altogether. Here's a good example: https://www.versalifthome.com/versa-lift/versa-lifttm-model-32

**Comment by evgk** [comment]
> That I agree with, I can see cases where you really wouldn't want a particular combination offered.

Ok, but then - the system already allows you to represent both cases on the database schema level - if a variation is defined per a certain combination of options, it exists as a variation, and if it doesn't exist in the variation table, it's an invalid combination of options. So why not just make the UI match this?

**Comment by Mesuva** [comment]
I'm not disagreeing with you, we can certainly work towards this, but we have to be able continue to support the current behaviour and not change it. We need to _add_ some sort of option to hide variations that we don't want to ever offer.

**Comment by evgk** [comment]
> We need to add some sort of option to hide variations that we don't want to ever offer.

But that's weird - adding an option to hide a variation would imply this variation exists. You would normally place this option on variation itself, and if it doesn't exist, then there is nowhere to place it to.

> but we have to be able continue to support the current behavior and not change it

Hmm, but how does it change the current behavior? You can't order do anything to a variation that doesn't exist in the database.

**Comment by evgk** [comment]
> You would normally place this option on variation itself, and if it doesn't exist, then there is nowhere to place it to.

I mean, the most natural way to represent that is how it's already represented in the database - a variation doesn't exist if there is no entry in the variation-table.

**Comment by Mesuva** [comment]
That's not quite how variations work in terms of the database. Variations are automatically created from every combination of option that is included in variations.  If you have two options in variations, one with 3 values and the other with 2, you'll have 6 variations in total.  A variation exists due to a combination of option, not because of an entry in a database table.

At present, all you can do is mark a variation as out of stock, and this is reflected on the front end when you pick the combination for that variation.  What you're suggesting is that you would then be able to for that particular combination check something that say 'this doesn't actually exist'. The interface would then prevent you from selecting it completely.

**Comment by evgk** [comment]
> That's not quite how variations work in terms of the database.

Hmm, that's where the difference is then - with POS integration that we're using, I'm just writing the individual variations that exist in POS - it wouldn't make sense to create all variations.

**Comment by evgk** [comment]
Hmm, but then I would say that such implementation is a little bit weird and not in line with how it works in other systems. In Magento, for instance, you can create a child product for a combination of options, but you can also remove the variations that do not make any sense / should not exist.

**Comment by evgk** [comment]
Since it's just a child product in Magento, removing a variation means deleting that child product. But it seems to me that what I suggested above is still a most natural way to implement it. A variation represents a physical product with a combination of options - like color and size. If such physical product cannot exist, the variation should not exist in the database as well.

**Comment by Mesuva** [comment]
I again don't disagree with you, and  I understand why you might be doing that, you're right in that it doesn't make sense to write data that you don't have.

But as it currently stands you're effectively writing to the database what Community Store would consider incomplete database records. There's no way to create what you are doing manually with the database via the the interface.  If you import a product this way, and then go in and save it, Community Store will then go and create the missing variation records in the database. 

It really comes down to how Community Store's variations just don't work quite the same way as Magento's child products, they're generated a differently/automatically.

So I think we need to find some way to exclude variations. This could be via the interface as a switch, but _also_ due to the variation record being absent. But again, that needs to be a layer on top of what we already have. And a further challenge is handling what happens if a save via the interface is performed, ensuring that absent variations aren't created (or are at least automatically flagged as excluded).

The code you submitted and I removed isn't lost, it'll still be available to reference in github, we just might need to find a different way to utilise it.

**Comment by Mesuva** [comment]
No necessarily, as often products are initially added and then configured with options at a later time, or a new option value is added into the mix.  But I get your point about effectively locking the variations, I'll give it some thought.

**Pull request merged**
